### ISSUE TITLE
Error running CpG model

### ISSUE THREAD

**Issue by hui-tony-zk** [cangermueller/deepcpg#1]
Hi,

When running `dcpg_train.py`, I encounter the following error:

```
Traceback (most recent call last):
  File "/home/thui/anaconda3/envs/deepcpg/bin/dcpg_train.py", line 4, in <module>
    __import__('pkg_resources').run_script('deepcpg==1.0.3', 'dcpg_train.py')
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/setuptools-27.2.0-py3.4.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_train.py", line 828, in <module>
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_train.py", line 192, in run
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_train.py", line 699, in main
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_train.py", line 569, in build_model
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_train.py", line 549, in build_cpg_model
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/deepcpg/models/cpg.py", line 86, in __call__
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/deepcpg/models/cpg.py", line 76, in _replicate_model
AttributeError: 'module' object has no attribute 'WeightRegularizer'
```

I also tried calling on the attribute directly (inspired from https://github.com/cangermueller/deepcpg/blob/master/deepcpg/models/cpg.py):

```
>>> from keras import regularizers as kr
Using Theano backend.
>>> kr.WeightRegularizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'WeightRegularizer'
```

I'm using python 3.4.5 (Anaconda distribution), with Theano (version 0.9.0) as the backend to Keras (version 2.0.3). I installed deepcpg using `python setup.py install` rather than `pip`, because the `.py` scripts weren't being correctly added to path by pip

**Comment by cangermueller** [comment]
Hi Hui,

I suspect that you are using Keras 2.X, which is not yet supported. I will add Keras 2.X until Wed. In the meantime, please use Keras 1.2.2.

- Christof

**Comment by hui-tony-zk** [comment]
That fixed it, thanks!

Tony

**Comment by cangermueller** [comment]
The DeepCpG branch [keras2](https://github.com/cangermueller/deepcpg/tree/keras2) adds Keras 2.x support. Everything works so far, except from loading models trained with Keras 1.x. It will be merged into the master branch once this is possible.
