### ISSUE TITLE
Error in dcpg_eval.py: TypeError: len() of unsized object

### ISSUE THREAD

**Issue by hui-tony-zk** [cangermueller/deepcpg#11]
```
Traceback (most recent call last):
  File "/home/thui/anaconda3/envs/deepcpg/bin/dcpg_eval.py", line 4, in <module>
    __import__('pkg_resources').run_script('deepcpg==1.0.3', 'dcpg_eval.py')
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_eval.py", line 254, in <module>
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_eval.py", line 96, in run
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_eval.py", line 221, in main
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_eval.py", line 76, in write_dict
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/deepcpg-1.0.3-py3.4.egg/EGG-INFO/scripts/dcpg_eval.py", line 81, in write_dict
TypeError: len() of unsized object
Exception ignored in: <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x7f0eaff6d128>>
Traceback (most recent call last):
  File "/home/thui/anaconda3/envs/deepcpg/lib/python3.4/site-packages/tensorflow/python/client/session.py", line 587, in __del__
AttributeError: 'NoneType' object has no attribute 'TF_NewStatus'
```

My command: `dcpg_eval.py ./data/*.h5 --model_files ./model/cpg/model.json ./model/cpg/model_weights_val.h5 --out_data ./eval/data.h5 --out_report ./eval/report.tsv`

My environment: 
```
(deepcpg) thui@devbox01:$ pip freeze
appdirs==1.4.3
cycler==0.10.0
deepcpg==1.0.4
h5py==2.7.0
Keras==1.2.2
matplotlib==2.0.1
numpy==1.12.1
numpydoc==0.6.0
packaging==16.8
pandas==0.20.1
protobuf==3.3.0
py==1.4.33
pyparsing==2.2.0
pytest==3.0.7
python-dateutil==2.6.0
pytz==2017.2
PyYAML==3.12
scikit-learn==0.18.1
scipy==0.19.0
seaborn==0.7.1
six==1.10.0
tensorflow==1.1.0
tensorflow-gpu==1.1.0
Theano==0.9.0
Werkzeug==0.12.1
```

**Comment by cangermueller** [comment]
Please update to Keras>=2.0.2.
