### ISSUE TITLE
Error in dcpg_train.py

### ISSUE THREAD

**Issue by timpeters82** [cangermueller/deepcpg#21]
Hi Christof,
Fantastic looking piece of software, but unfortunately I've encountered an error when starting to train the data.

```
~/scratch/deepCpG$ dcpg_train.py c1_*.h5 c3_*.h5 c5_*.h5 --val_files c2_*.h5 --dna_model CnnL2h128 --cpg_model RnnL1 --out_dir models --nb_epoch 30
Using TensorFlow backend.
INFO (2018-07-23 12:21:21,556): Building model ...
INFO (2018-07-23 12:21:21,558): Building DNA model ...
Traceback (most recent call last):
  File "/usr/local/bin/dcpg_train.py", line 4, in <module>
    __import__('pkg_resources').run_script('deepcpg==1.0.6', 'dcpg_train.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/deepcpg-1.0.6-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 836, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/deepcpg-1.0.6-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 194, in run
    
  File "/usr/local/lib/python2.7/dist-packages/deepcpg-1.0.6-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 705, in main
    
  File "/usr/local/lib/python2.7/dist-packages/deepcpg-1.0.6-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 571, in build_model
    
  File "/usr/local/lib/python2.7/dist-packages/deepcpg-1.0.6-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 508, in build_dna_model
    
  File "build/bdist.linux-x86_64/egg/deepcpg/models/dna.py", line 117, in __call__
  File "build/bdist.linux-x86_64/egg/deepcpg/models/utils.py", line 448, in _build
AttributeError: 'Model' object has no attribute 'input_layers'

```
Any ideas on how I can fix this? Any help would be much appreciated.

Best,
Tim

**Comment by timpeters82** [comment]
Also, here are my versions of Keras and Tensorflow:
```
~/scratch/deepCpG$ python -c 'import keras; print(keras.__version__)'
Using TensorFlow backend.
2.2.0
~/scratch/deepCpG$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.9.0
```

**Comment by cangermueller** [comment]
DeepCpG does not support Keras 2.2.X yet. Please downgrade to Keras 2.1.X. I am about to fix this.

**Comment by timpeters82** [comment]
Thanks Christof, all working now with Keras 2.1.6.

Cheers,
Tim
