### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WeightRegularizer'

### ISSUE THREAD

**Issue by IamMegatron2025** [cangermueller/deepcpg#6]
hello, when I run` bash train,sh` in `examples/scripts`, it shows error:

```
#################################
dcpg_train.py ./data/c{1,3,5,7,9}*.h5 --val_files ./data/c{1,3,5,7,9}*.h5 --out_dir ./models/dna --dna_model CnnL2h128 --val_files ./data/c{1,3,5,7,9}*.h5 --nb_train_sample 500 --nb_val_sample 500 --nb_epoch 1
#################################
Using TensorFlow backend.
INFO (2017-06-01 11:00:40,810): Building model ...
INFO (2017-06-01 11:00:40,811): Building DNA model ...
Traceback (most recent call last):
  File "/home/ztgong/local/anaconda2/bin/dcpg_train.py", line 4, in <module>
    __import__('pkg_resources').run_script('deepcpg==1.0.4', 'dcpg_train.py')
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/deepcpg-1.0.4-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 828, in <module>
    
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/deepcpg-1.0.4-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 192, in run
    
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/deepcpg-1.0.4-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 699, in main
    
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/deepcpg-1.0.4-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 565, in build_model
    
  File "/home/ztgong/local/anaconda2/lib/python2.7/site-packages/deepcpg-1.0.4-py2.7.egg/EGG-INFO/scripts/dcpg_train.py", line 502, in build_dna_model
    
  File "build/bdist.linux-x86_64/egg/deepcpg/models/dna.py", line 90, in __call__
AttributeError: 'module' object has no attribute 'WeightRegularizer'
```
I refer to keras documentation. There is `keras.regularizers.WeightRegularizer`, so why it reports an error here?
how to fix it? thank you very much~
looking forward to your reply~ 

my python version is 2.7 and keras version is 2.0.3/2.0.4.

**Comment by IamMegatron2025** [comment]
I have solve it through [issue](https://github.com/cangermueller/deepcpg/issues/1).
thankyou very much!
